// Generated by scripts/sync-iptv-channels.mjs from https://garysclub.sharewithyou.dpdns.org/others/ysp-live.py
// Regenerate with: node scripts/sync-iptv-channels.mjs [--input <saved ysp-live.py>]

export interface IptvChannel {
  slug: string;
  name: string;
  sid: string;
  pid: string;
  defn: string;
  tvgId?: string;
  timeshift: boolean;
}

export const IPTV_LOGO_BASE = "https://garysclub.sharewithyou.dpdns.org/logos/ysp-live-logos";
export const IPTV_EPG_URLS: readonly string[] = ["https://live.fanmingming.com/e.xml","https://epg.112114.xyz/pp.xml.gz"];

export const IPTV_CHANNELS: readonly IptvChannel[] = [
  {"slug":"cctv1","name":"CCTV-1 综合","sid":"2024078201","pid":"600001859","defn":"fhd","tvgId":"CCTV1","timeshift":true},
  {"slug":"cctv2","name":"CCTV-2 财经","sid":"2024075401","pid":"600001800","defn":"fhd","tvgId":"CCTV2","timeshift":true},
  {"slug":"cctv3","name":"CCTV-3 综艺","sid":"2024068501","pid":"600001801","defn":"fhd","tvgId":"CCTV3","timeshift":true},
  {"slug":"cctv4","name":"CCTV-4 中文国际","sid":"2029797101","pid":"600001814","defn":"fhd","tvgId":"CCTV4","timeshift":true},
  {"slug":"cctv5","name":"CCTV-5 体育","sid":"2024078401","pid":"600001818","defn":"fhd","tvgId":"CCTV5","timeshift":true},
  {"slug":"cctv5p","name":"CCTV-5+ 体育赛事","sid":"2024078001","pid":"600001817","defn":"fhd","tvgId":"CCTV5+","timeshift":true},
  {"slug":"cctv6","name":"CCTV-6 电影","sid":"2013693901","pid":"600108442","defn":"fhd","tvgId":"CCTV6","timeshift":true},
  {"slug":"cctv7","name":"CCTV-7 国防军事","sid":"2024072001","pid":"600004092","defn":"fhd","tvgId":"CCTV7","timeshift":true},
  {"slug":"cctv8","name":"CCTV-8 电视剧","sid":"2029793001","pid":"600001803","defn":"fhd","tvgId":"CCTV8","timeshift":true},
  {"slug":"cctv9","name":"CCTV-9 纪录","sid":"2024078601","pid":"600004078","defn":"fhd","tvgId":"CCTV9","timeshift":true},
  {"slug":"cctv10","name":"CCTV-10 科教","sid":"2024078701","pid":"600001805","defn":"fhd","tvgId":"CCTV10","timeshift":true},
  {"slug":"cctv11","name":"CCTV-11 戏曲","sid":"2027248701","pid":"600001806","defn":"fhd","tvgId":"CCTV11","timeshift":false},
  {"slug":"cctv12","name":"CCTV-12 社会与法","sid":"2027248801","pid":"600001807","defn":"fhd","tvgId":"CCTV12","timeshift":false},
  {"slug":"cctv13","name":"CCTV-13 新闻","sid":"2029797201","pid":"600001811","defn":"fhd","tvgId":"CCTV13","timeshift":true},
  {"slug":"cctv14","name":"CCTV-14 少儿","sid":"2027248901","pid":"600001809","defn":"fhd","tvgId":"CCTV14","timeshift":false},
  {"slug":"cctv15","name":"CCTV-15 音乐","sid":"2027249001","pid":"600001815","defn":"fhd","tvgId":"CCTV15","timeshift":false},
  {"slug":"cctv16","name":"CCTV-16 奥林匹克","sid":"2027249101","pid":"600098637","defn":"fhd","tvgId":"CCTV16","timeshift":false},
  {"slug":"cctv164k","name":"CCTV-16 4K","sid":"2027249301","pid":"600099502","defn":"fhd","tvgId":"CCTV16","timeshift":false},
  {"slug":"cctv17","name":"CCTV-17 农业农村","sid":"2027249401","pid":"600001810","defn":"fhd","tvgId":"CCTV17","timeshift":false},
  {"slug":"cctv4k","name":"CCTV-4K 超高清","sid":"2029810301","pid":"600002264","defn":"fhd","tvgId":"CCTV4K","timeshift":false},
  {"slug":"cctv8k","name":"CCTV-8K 超高清","sid":"2026774101","pid":"600156816","defn":"fhd","tvgId":"CCTV-8K","timeshift":true},
  {"slug":"cgtn","name":"CGTN","sid":"2024181701","pid":"600014550","defn":"fhd","tvgId":"CGTN英语","timeshift":true},
  {"slug":"cgtnfr","name":"CGTN 法语","sid":"2024181801","pid":"600084704","defn":"fhd","tvgId":"CGTN法语","timeshift":true},
  {"slug":"cgtnru","name":"CGTN 俄语","sid":"2024181901","pid":"600084758","defn":"fhd","tvgId":"CGTN俄语","timeshift":true},
  {"slug":"cgtnar","name":"CGTN 阿拉伯语","sid":"2024182001","pid":"600084782","defn":"fhd","tvgId":"CGTN阿语","timeshift":true},
  {"slug":"cgtnes","name":"CGTN 西班牙语","sid":"2024182101","pid":"600084744","defn":"fhd","tvgId":"CGTN西语","timeshift":true},
  {"slug":"cgtndoc","name":"CGTN 纪录","sid":"2024182301","pid":"600084781","defn":"fhd","tvgId":"CGTN纪录","timeshift":true},
  {"slug":"cctvfyjc","name":"CCTV 风云剧场","sid":"2025637102","pid":"600099658","defn":"shd","tvgId":"CCTV风云剧场","timeshift":false},
  {"slug":"cctvdyjc","name":"CCTV 第一剧场","sid":"2026874202","pid":"600099655","defn":"shd","tvgId":"CCTV第一剧场","timeshift":false},
  {"slug":"cctvhjjc","name":"CCTV 怀旧剧场","sid":"2026874302","pid":"600099620","defn":"shd","tvgId":"CCTV怀旧剧场","timeshift":false},
  {"slug":"bjws","name":"北京卫视","sid":"2024052703","pid":"600002309","defn":"fhd","tvgId":"北京卫视","timeshift":true},
  {"slug":"jsws","name":"江苏卫视","sid":"2024171103","pid":"600002521","defn":"fhd","tvgId":"江苏卫视","timeshift":true},
  {"slug":"dfws","name":"东方卫视","sid":"2024054503","pid":"600002483","defn":"fhd","tvgId":"东方卫视","timeshift":true},
  {"slug":"zjws","name":"浙江卫视","sid":"2024054703","pid":"600002520","defn":"fhd","tvgId":"浙江卫视","timeshift":true},
  {"slug":"hnws","name":"湖南卫视","sid":"2024054803","pid":"600002475","defn":"fhd","tvgId":"湖南卫视","timeshift":true},
  {"slug":"hbws","name":"湖北卫视","sid":"2024171203","pid":"600002508","defn":"fhd","tvgId":"湖北卫视","timeshift":true},
  {"slug":"gdws","name":"广东卫视","sid":"2024060903","pid":"600002485","defn":"fhd","tvgId":"广东卫视","timeshift":true},
  {"slug":"gxws","name":"广西卫视","sid":"2024060703","pid":"600002509","defn":"fhd","tvgId":"广西卫视","timeshift":true},
  {"slug":"hljws","name":"黑龙江卫视","sid":"2029797003","pid":"600002498","defn":"fhd","tvgId":"黑龙江卫视","timeshift":true},
  {"slug":"hainanws","name":"海南卫视","sid":"2024055603","pid":"600002506","defn":"fhd","tvgId":"海南卫视","timeshift":true},
  {"slug":"cqws","name":"重庆卫视","sid":"2024061103","pid":"600002531","defn":"fhd","tvgId":"重庆卫视","timeshift":true},
  {"slug":"szws","name":"深圳卫视","sid":"2024061303","pid":"600002481","defn":"fhd","tvgId":"深圳卫视","timeshift":true},
  {"slug":"scws","name":"四川卫视","sid":"2024061403","pid":"600002516","defn":"fhd","tvgId":"四川卫视","timeshift":true},
  {"slug":"henanws","name":"河南卫视","sid":"2029797303","pid":"600002525","defn":"fhd","tvgId":"河南卫视","timeshift":true},
  {"slug":"dnws","name":"东南卫视","sid":"2024061503","pid":"600002484","defn":"fhd","tvgId":"东南卫视","timeshift":true},
  {"slug":"gzws","name":"贵州卫视","sid":"2024061603","pid":"600002490","defn":"fhd","tvgId":"贵州卫视","timeshift":true},
  {"slug":"jxws","name":"江西卫视","sid":"2024061703","pid":"600002503","defn":"fhd","tvgId":"江西卫视","timeshift":true},
  {"slug":"lnws","name":"辽宁卫视","sid":"2024171303","pid":"600002505","defn":"fhd","tvgId":"辽宁卫视","timeshift":true},
  {"slug":"ahws","name":"安徽卫视","sid":"2024171403","pid":"600002532","defn":"fhd","tvgId":"安徽卫视","timeshift":true},
  {"slug":"hebws","name":"河北卫视","sid":"2024171503","pid":"600002493","defn":"fhd","tvgId":"河北卫视","timeshift":true},
  {"slug":"sdws","name":"山东卫视","sid":"2029787903","pid":"600002513","defn":"fhd","tvgId":"山东卫视","timeshift":true},
  {"slug":"tjws","name":"天津卫视","sid":"2019927003","pid":"600152137","defn":"fhd","tvgId":"天津卫视","timeshift":true},
  {"slug":"jlws","name":"吉林卫视","sid":"2025561503","pid":"600190405","defn":"fhd","tvgId":"吉林卫视","timeshift":true},
  {"slug":"saxws","name":"陕西卫视","sid":"2029795103","pid":"600190400","defn":"fhd","tvgId":"陕西卫视","timeshift":true},
  {"slug":"nxws","name":"宁夏卫视","sid":"2025608503","pid":"600190737","defn":"fhd","tvgId":"宁夏卫视","timeshift":true},
  {"slug":"nmgws","name":"内蒙古卫视","sid":"2025561203","pid":"600190401","defn":"fhd","tvgId":"内蒙古卫视","timeshift":true},
  {"slug":"ynws","name":"云南卫视","sid":"2025561303","pid":"600190402","defn":"fhd","tvgId":"云南卫视","timeshift":true},
  {"slug":"shanxiws","name":"山西卫视","sid":"2025560803","pid":"600190407","defn":"fhd","tvgId":"山西卫视","timeshift":true},
  {"slug":"gsws","name":"甘肃卫视","sid":"2025561703","pid":"600190408","defn":"fhd","tvgId":"甘肃卫视","timeshift":true},
  {"slug":"qhws","name":"青海卫视","sid":"2025559103","pid":"600190406","defn":"fhd","tvgId":"青海卫视","timeshift":true},
  {"slug":"xizangws","name":"西藏卫视","sid":"2025558003","pid":"600190403","defn":"fhd","tvgId":"西藏卫视","timeshift":true},
  {"slug":"xjws","name":"新疆卫视","sid":"2019927403","pid":"600152138","defn":"fhd","tvgId":"新疆卫视","timeshift":true},
  {"slug":"cetv1","name":"CETV-1","sid":"2022823801","pid":"600171827","defn":"fhd","tvgId":"CETV1","timeshift":true},
  {"slug":"guoxue","name":"国学频道","sid":"2029360403","pid":"600213139","defn":"fhd","tvgId":"国学","timeshift":true},
];

export function iptvChannelGroup(slug: string): string {
  if (slug.endsWith('ws')) return '卫视频道';
  if (slug.includes('jc') || slug === 'guoxue') return '数字频道';
  return '央视频道';
}

export function getIptvChannel(slug: string): IptvChannel | undefined {
  return IPTV_CHANNELS.find((channel) => channel.slug === slug);
}
