[package]
name = "tjxy-cache"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
redis = { version = "1.4.1", features = ["tokio-comp", "connection-manager"] }
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
