/* eslint-disable @typescript-eslint/no-unnecessary-condition, @typescript-eslint/restrict-template-expressions */
import { Alert, Button, Skeleton } from '@heroui/react';
import { ArrowLeft, CircleAlert } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getItem, type MediaItem } from '../api/catalogApi';
import { getPlaybackInfo, issuePlaybackTicket, revokePlaybackTicket, type PlaybackTicket } from '../api/playbackApi';
import { selectBrowserSource } from './sourceSelection';
export function PlayerPage() { const { id } = useParams(); const videoRef = useRef<HTMLVideoElement>(null); const [item, setItem] = useState<MediaItem>(); const [ticket, setTicket] = useState<PlaybackTicket>(); const [error, setError] = useState(false); const [unsupported, setUnsupported] = useState(false); useEffect(() => { if (!id) return; let active = true; void Promise.all([getItem(id), getPlaybackInfo(id)]).then(async ([nextItem, playback]) => { if (!active || !playback.PlaySessionId) throw new Error('unavailable'); const source = selectBrowserSource(playback.MediaSources ?? []); if (!source) { setUnsupported(true); return; } const issued = await issuePlaybackTicket(id, source.Id, playback.PlaySessionId); if (active) { setItem(nextItem); setTicket(issued); } }).catch(() => { if (active) setError(true); }); return () => { active = false; }; }, [id]); useEffect(() => () => { if (ticket) void revokePlaybackTicket(ticket.Id).catch(() => undefined); }, [ticket]); if (error) return <Alert status="danger"><Alert.Indicator><CircleAlert className="size-4" /></Alert.Indicator><Alert.Content><Alert.Title>Playback unavailable</Alert.Title><Alert.Description>We could not prepare this title right now.</Alert.Description></Alert.Content></Alert>; if (unsupported) return <div className="space-y-4"><Link className="inline-flex items-center gap-2 text-sm text-muted" to={`/app/items/${id}`}><ArrowLeft className="size-4" />Back to details</Link><Alert status="warning"><Alert.Content><Alert.Title>This format is not supported in your browser</Alert.Title><Alert.Description>Choose an MP4, WebM, MP3, M4A, or Ogg source.</Alert.Description></Alert.Content></Alert></div>; if (!item || !ticket) return <Skeleton className="aspect-video w-full rounded-2xl" />; return <div className="space-y-5"><div className="flex items-center justify-between"><Link className="inline-flex items-center gap-2 text-sm text-muted" to={`/app/items/${id}`}><ArrowLeft className="size-4" />Back to details</Link><Button onPress={() => { if (videoRef.current) videoRef.current.pause(); }} variant="tertiary">Exit</Button></div><div className="overflow-hidden rounded-2xl bg-black"><video aria-label={`Playing ${item.Name}`} className="aspect-video w-full" controls onEnded={() => { if (ticket) void revokePlaybackTicket(ticket.Id).catch(() => undefined); }} ref={videoRef} src={ticket.StreamUrl} /></div><div><h1 className="text-2xl font-semibold">{item.Name}</h1><p className="mt-1 text-sm text-muted">Direct playback</p></div></div>; }
