/* eslint-disable @typescript-eslint/no-misused-promises */
import { Button, Chip, Skeleton } from '@heroui/react';
import { Heart, Play } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { getItem, toggleFavorite, togglePlayed, type MediaItem } from '../api/catalogApi';
import { MediaImage } from '../ui/MediaImage';
import { useClientAuth } from '../auth/ClientAuthContext';
export function ItemPage() { const { id } = useParams(); const navigate = useNavigate(); const { user } = useClientAuth(); const [item, setItem] = useState<MediaItem>(); useEffect(() => { if (id) void getItem(id).then(setItem); }, [id]); if (!item || !id) return <Skeleton className="h-96 rounded-2xl" />; const favorite = item.UserData?.IsFavorite === true; const played = item.UserData?.Played === true; return <article className="space-y-8"><Link className="text-sm text-muted hover:text-foreground" to="/app/">← Back to home</Link><div className="grid gap-8 md:grid-cols-[16rem_minmax(0,1fr)]"><div className="aspect-[2/3] overflow-hidden rounded-2xl bg-default"><MediaImage alt={`Poster for ${item.Name}`} className="h-full w-full object-cover" itemId={id} tag={item.ImageTags?.Primary} /></div><div className="self-center"><div className="flex flex-wrap gap-2"><Chip>{item.Type ?? 'Media'}</Chip>{item.ProductionYear && <Chip variant="secondary">{item.ProductionYear}</Chip>}</div><h1 className="mt-4 text-4xl font-semibold">{item.Name}</h1>{item.Overview && <p className="mt-5 max-w-2xl text-base leading-7 text-muted">{item.Overview}</p>}<div className="mt-7 flex flex-wrap gap-3"><Button onPress={() => navigate(`/app/play/${id}`)}><Play className="size-4" />Play</Button><Button variant="secondary" onPress={() => { if (user) void toggleFavorite(user.Id, id, !favorite).then(() => { setItem({ ...item, UserData: { ...item.UserData, IsFavorite: !favorite } }); }); }}><Heart className="size-4" />{favorite ? 'Unfavorite' : 'Favorite'}</Button><Button variant="tertiary" onPress={() => { if (user) void togglePlayed(user.Id, id, !played).then(() => { setItem({ ...item, UserData: { ...item.UserData, Played: !played } }); }); }}>{played ? 'Mark unplayed' : 'Mark played'}</Button></div></div></div></article>; }
